<?php
/**
 * View for main plugin settings page
 */
?>
<div class="tt-logo-plugin-container">
    <h1 class="tt-plugin-title"><?php echo esc_html($page_title) ?></h1>
    <p class="tt-plugin-description"><?php _e('Customize your login page with ease','tt_login') ?></p>
    <?php do_action( 'tt_login_admin_notices' ) ?>
    <h1 class="nav-tab-wrapper tt-nav-wrapper">
        <?php
        /*
         * Calls tabslinks  generated by add_tab() method
         */
        do_action( 'tt_login_admin_tabs_links_' . $page_id );?>
        <a href="<?php echo wp_login_url() ?>" target="_blank" class="tt-login-preview button-primary">
            <span class="dashicons dashicons-visibility"></span>
            <?php _e('Login Page','tt_login') ?>
        </a>
    </h1>
    <div class="tabs-content-wrapper">
        <?php
        /*
         * Calls tabs content generated by add_tab() method
         */
        do_action( 'tt_login_admin_tabs_contents_' . $page_id ); ?>
    </div>
</div>